// category.types.js
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const ERROR_CATEGORIES = "ERROR_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SUCCESS_CATEGORIES = "SUCCESS_CATEGORIES";
export const GET_CATEGORY_ID = "GET_CATEGORY_ID";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES"; 
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES"; 
