export const LOADING_TRANSACTION="parties/LOADING_TRANSACTION";
export const SUCCESS_TRANSACTION="parties/SUCCESS_TRANSACTION";
export const ERROR_TRANSACTION="parties/ERROR_TRANSACTION";

export const GET_TRANSACTION="parties/GET_TRANSACTION";
export const UPDATE_TRANSACTION="parties/UPDATE_TRANSACTION";
export const DELETE_TRANSACTION="parties/DELETE_TRANSACTION";


