export const LOADING_FIRM_REGISTER = "register/LOADING_FIRM_REGISTER";
export const SUCCESS_FIRM_REGISTER = "register/SUCCESS_FIRM_REGISTER";
export const ERROR_FIRM_REGISTER = "register/ERROR_FIRM_REGISTER";

export const SUCCESS_GET_FIRM_REGISTER="register/SUCCESS_GET_FIRM_REGISTER";


export const SET_FIRM_ID="firm/SET_FIRM_ID";
export const SET_FIRM_NAME="firm/SET_FIRM_NAME";