export const LOADING_STOCKS="STOCKS/LOADING_STOCKS";
export const SUCCESS_STOCKS="STOCKS/SUCCESS_STOCKS";
export const ERROR_STOCKS="STOCKS/ERROR_STOCKS";

export const GET_STOCKS="STOCKS/GET_STOCKS";
export const UPDATE_STOCKS="STOCKS/UPDATE_STOCKS";
export const DELETE_STOCKS="STOCKS/DELETE_STOCKS";


