export const LOADING_PURCHASEOUT="parties/LOADING_PURCHASEOUT";
export const SUCCESS_PURCHASEOUT="parties/SUCCESS_PURCHASEOUT";
export const ERROR_PURCHASEOUT="parties/ERROR_PURCHASEOUT";

export const GET_PURCHASEOUT="parties/GET_PURCHASEOUT";
export const UPDATE_PURCHASEOUT="parties/UPDATE_PURCHASEOUT";
export const DELETE_PURCHASEOUT="parties/DELETE_PURCHASEOUT";
