export const LOADING_INVOICE="INVOICE/LOADING_INVOICE";
export const SUCCESS_INVOICE="INVOICE/SUCCESS_INVOICE";
export const ERROR_INVOICE="INVOICE/ERROR_INVOICE";
export const GET_INVOICE="INVOICE/GET_INVOICE";
export const GET_ONE_INVOICE="INVOICE/GET_ONE_INVOICE";
export const UPDATE_INVOICE="INVOICE/UPDATE_INVOICE";
export const DELETE_INVOICE="INVOICE/DELETE_INVOICE";


