export const LOADING_VENDOR_LOGIN = "VENDOR_login/LOADING_VENDOR_LOGIN";
export const SUCCESS_VENDOR_LOGIN = "VENDOR_login/SUCCESS_VENDOR_LOGIN";
export const ERROR_VENDOR_LOGIN = "VENDOR_login/ERROR_VENDOR_LOGIN";

export const SUCCESS_LOGOUT = "logout/SUCCESS_LOGOUT";